# Generated by Django 4.0.4 on 2022-05-09 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_gearorder_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonialText', models.TextField(max_length=1000)),
                ('wrestler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='gear.wrestler')),
            ],
        ),
    ]
