# Generated by Django 4.0.4 on 2022-05-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearorder',
            name='hasPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gearorder',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gearorder',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
