# Generated by Django 4.0.4 on 2022-05-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0005_remove_galleryitem_photourl_galleryphotoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphotoitem',
            name='galleryItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photo_items', to='gear.galleryitem'),
        ),
    ]
